// Importing images
import Amoxicillin0 from '../../../assets/drugs/Amoxicillin0.jpg';
import Tetracycline0 from '../../../assets/drugs/Tetracycline0.jpg';
import Flucloxacillin0 from '../../../assets/drugs/Flucloxacillin0.webp';
import Ampicillin0 from '../../../assets/drugs/Ampicillin0.webp';
import Chloramphenicol0 from '../../../assets/drugs/Chloramphenicol0.webp';
import Penicillin0 from '../../../assets/drugs/Penicillin0.jpg';
import Amciclox0 from '../../../assets/drugs/Ampiclox.jpg';
import Ciprolex0 from '../../../assets/drugs/Ciprolex0.jpg';
import Cefuroxime0 from '../../../assets/drugs/Cefuroxime0.jpg';
import Amoxiclav0 from '../../../assets/drugs/Amoxiclav0.jpg';
import Fluconazole0 from '../../../assets/drugs/Fluconazole0.jpg';

const AntibioticsData = [
    {
        id: 0,
        drugName: "Amoxicillin",
        description: "Amoxicillin is used to treat a wide variety of bacterial infections.",
        image0: Amoxicillin0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 1,
        drugName: "Tetracycline",
        description: "Tetracycline is used to treat acne and infections caused by bacteria.",
        image0: Tetracycline0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 2,
        drugName: "Flucloxacillin",
        description: "Flucloxacillin is used to treat bacterial infections.",
        image0: Flucloxacillin0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 3,
        drugName: "Ampicillin",
        description: "Ampicillin is used to treat a wide variety of bacterial infections.",
        image0: Ampicillin0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 4,
        drugName: "Chloramphenicol",
        description: "Chloramphenicol is used to treat serious bacterial infections.",
        image0: Chloramphenicol0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 5,
        drugName: "Penicillin",
        description: "Penicillin is used to treat a variety of bacterial infections.",
        image0: Penicillin0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 6,
        drugName: "Amciclox",
        description: "Amciclox is used to treat bacterial infections.",
        image0: Amciclox0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 7,
        drugName: "Ciprolex",
        description: "Ciprolex is used to treat a variety of bacterial infections.",
        image0: Ciprolex0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 8,
        drugName: "Cefuroxime",
        description: "Cefuroxime is used to treat a wide variety of bacterial infections.",
        image0: Cefuroxime0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 9,
        drugName: "Amoxiclav",
        description: "Amoxiclav is used to treat a variety of bacterial infections.",
        image0: Amoxiclav0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
    {
        id: 10,
        drugName: "Fluconazole",
        description: "Fluconazole is used to treat fungal infections.",
        image0: Fluconazole0,
        image1: '',
        image2: '',
        inStock: true,
        price: "GHS 100.00",
        whatItDoes: "",
        keyComponents: "",
    },
];

export default AntibioticsData;