const AntibioticsData = [
    {
        id: 0,
        drugName: "Amoxicillin",
        description: "",
        image0: require("../../../assets/drugs/Amoxicillin0.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 1,
        drugName: "Tetracycline",
        description: "",
        image0: require("../../../assets/drugs/Tetracycline0.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 2,
        drugName: "Flucloxacillin",
        description: "",
        image0: require("../../../assets/drugs/Fluconazole0.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 3,
        drugName: "Ampicillin",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 4,
        drugName: "Chloramphenicol",
        description: "",
        image0: require("../../../assets/drugs/Chloramphenicol0.webp"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 5,
        drugName: "Penicillin",
        description: "",
        image0: require("../../../assets/drugs/Penicillin0.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 6,
        drugName: "Amciclox",
        description: "",
        image0: require("../../../assets/drugs/Ampiclox.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 7,
        drugName: "Ciprolex",
        description: "",
        image0: require("../../../assets/drugs/Ciprolex0.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 8,
        drugName: "Cefurixime",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 9,
        drugName: "Amoxiclav",
        description: "",
        image0: require("../../../assets/drugs/Amoxiclav0.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
    {
        id: 10,
        drugName: "Fluconazole",
        description: "",
        image0: require("../../../assets/drugs/Fluconazole0.jpg"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
        price: "GHS 100.00",
    },
];

export default AntibioticsData;