const Data = [
    {
        id: 0,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 1,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 2,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 3,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 4,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 5,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 6,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 7,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 8,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 9,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
    {
        id: 10,
        drugName: "",
        description: "",
        image0: require("../../../assets/drugs/"),
        image1: require("../../../assets/drugs/"),
        image2: require("../../../assets/drugs/"),
        inStock: true,
    },
];

export default Data;